version: '3.5'

services:
  php:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./app:/app
    environment:
      - VIRTUAL_HOST=php8.local.cben.dev

  lint:
    image: hadolint/hadolint
    volumes:
    - ./.hadolint.yaml:/root/.config/.hadolint.yaml:ro
    - ./Dockerfile:/Dockerfile:ro
    command: "hadolint /Dockerfile"

networks:
  default:
    external:
      name: global
