name: CI
on:
  push:
    branches: [ feature/templating ]

jobs:
  compile:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          # enter generator directory
          cd generator
          # build rust application
          cargo build --release
      - name: upload artifact
        uses: actions/upload-artifact@master
        with:
          name: generator
          path: generator/target/release/generator
  generate:
    runs-on: ubuntu-20.04
    needs: [compile]
    strategy:
      matrix:
        cli: [dev, prod]
        type: [alpine, debian, cli]
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - uses: actions/download-artifact@master
        with:
          name: generator
          path: generator/generator
      - name: generate dockerfiles
        run: generator/generator ${{ matrix.cli }} --type={{ matrix.type }}
      - name: lint dockerfiles
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "Dockerfile"
